### ISSUE TITLE
Hello, I'm a newbie. How can I package this into an APK?

### ISSUE THREAD

**Issue by 1SUUU2** [enenH/AndroidImgui#3]

**Comment by enenH** [comment]
Create a JNI project and add dependencies to the CMakeLists as described.

**Comment by 1SUUU2** [comment]
"Could you please provide more details?"

**Comment by 1SUUU2** [comment]
> Create a JNI project and add dependencies to the CMakeLists as described.

**Comment by 1SUUU2** [comment]
> Create a JNI project and add dependencies to the CMakeLists as described.


"Could you please provide more details?"
