### ISSUE TITLE
error: no member named 'contains' in 'std::unordered_map<

### ISSUE THREAD

**Issue by wode2016501** [enenH/AndroidImgui#5]
clang++: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
/media/wode/0e449915-b15f-4add-bf32-647e92a1d144/src/android/AndroidImgui-main/src/ANativeWindowCreator.h:274:34: error: no member named 'contains' in 'std::unordered_map<unsigned long, std::unordered_map<void **, const char *>>'
  274 |                 if (patchesTable.contains(systemVersion)) {
      |                     ~~~~~~~~~~~~ ^
/media/wode/0e449915-b15f-4add-bf32-647e92a1d144/src/android/AndroidImgui-main/src/ANativeWindowCreator.h:557:41: error: no member named 'contains' in 'std::unordered_map<ANativeWindow *, android::detail::SurfaceControl>'
  557 |             if (!m_cachedSurfaceControl.contains(nativeWindow))
      |                  ~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.

**Comment by enenH** [comment]
https://github.com/enenH/AndroidImgui/blob/2e7dc42864add353812a69c07aa6ff335d6a2e99/CMakeLists.txt#L17
